SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS system_settings (
  setting_key VARCHAR(80) PRIMARY KEY, setting_value TEXT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL,
  name_en VARCHAR(100) NULL, name_hu VARCHAR(100) NULL,
  sort_order INT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, type VARCHAR(20) NOT NULL,
  category_id BIGINT UNSIGNED NULL, name VARCHAR(100) NOT NULL, description VARCHAR(500) NULL,
  name_en VARCHAR(100) NULL, name_hu VARCHAR(100) NULL, description_en VARCHAR(500) NULL, description_hu VARCHAR(500) NULL,
  base_price DECIMAL(10,2) NOT NULL, image_url VARCHAR(500) NULL, sort_order INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL,
  INDEX idx_product_category (category_id), CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(id),
  CHECK (base_price >= 0), CHECK (type IN ('dish','package'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS package_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, package_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL, quantity INT UNSIGNED NOT NULL DEFAULT 1,
  UNIQUE KEY uk_package_product (package_id, product_id),
  FOREIGN KEY (package_id) REFERENCES products(id), FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS service_sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, service_date DATE NOT NULL, meal_type VARCHAR(20) NOT NULL,
  order_start_at DATETIME NOT NULL, cutoff_at DATETIME NOT NULL,
  enabled_delivery TINYINT(1) NOT NULL DEFAULT 1, enabled_takeaway TINYINT(1) NOT NULL DEFAULT 1,
  enabled_dine_in TINYINT(1) NOT NULL DEFAULT 1, status VARCHAR(20) NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_service_date_meal (service_date, meal_type), CHECK (cutoff_at > order_start_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS session_products (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, session_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL,
  sale_price DECIMAL(10,2) NOT NULL, stock INT UNSIGNED NULL COMMENT 'NULL means unlimited', sold_qty INT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'active', UNIQUE KEY uk_session_product (session_id, product_id),
  FOREIGN KEY (session_id) REFERENCES service_sessions(id), FOREIGN KEY (product_id) REFERENCES products(id),
  CHECK (sale_price >= 0), CHECK (stock IS NULL OR sold_qty <= stock)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS time_slots (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, session_id BIGINT UNSIGNED NOT NULL, fulfillment_type VARCHAR(20) NOT NULL,
  start_time TIME NOT NULL, end_time TIME NOT NULL, capacity INT UNSIGNED NOT NULL, used_capacity INT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'active', FOREIGN KEY (session_id) REFERENCES service_sessions(id),
  INDEX idx_slot_session_type (session_id, fulfillment_type), CHECK (end_time > start_time), CHECK (used_capacity <= capacity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS delivery_zones (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, name_en VARCHAR(100) NULL, name_hu VARCHAR(100) NULL, delivery_fee DECIMAL(10,2) NOT NULL DEFAULT 0,
  min_order_amount DECIMAL(10,2) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'active'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dining_tables (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, table_no VARCHAR(30) NOT NULL UNIQUE,
  capacity INT UNSIGNED NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_no VARCHAR(40) NOT NULL UNIQUE,
  idempotency_key VARCHAR(80) NOT NULL UNIQUE, query_token_hash CHAR(64) NOT NULL,
  fulfillment_code VARCHAR(12) NULL UNIQUE COMMENT '取餐码/配送码/就餐码',
  session_id BIGINT UNSIGNED NOT NULL, service_date DATE NOT NULL, meal_type VARCHAR(20) NOT NULL,
  fulfillment_type VARCHAR(20) NOT NULL, fulfillment_status VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending', payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
  customer_name VARCHAR(100) NOT NULL, customer_phone VARCHAR(30) NOT NULL, address VARCHAR(500) NULL,
  delivery_lat DECIMAL(10,7) NULL, delivery_lng DECIMAL(10,7) NULL,
  time_slot_id BIGINT UNSIGNED NOT NULL, delivery_zone_id BIGINT UNSIGNED NULL, people_count INT UNSIGNED NOT NULL DEFAULT 1,
  table_id BIGINT UNSIGNED NULL, remark VARCHAR(200) NULL, subtotal_amount DECIMAL(10,2) NOT NULL,
  delivery_fee DECIMAL(10,2) NOT NULL DEFAULT 0, discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  payable_amount DECIMAL(10,2) NOT NULL, cancel_reason VARCHAR(200) NULL, cancelled_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (session_id) REFERENCES service_sessions(id), FOREIGN KEY (time_slot_id) REFERENCES time_slots(id),
  INDEX idx_order_service (service_date, meal_type, status), INDEX idx_order_phone (customer_phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL,
  product_name VARCHAR(100) NOT NULL, product_type VARCHAR(20) NOT NULL, unit_price DECIMAL(10,2) NOT NULL,
  quantity INT UNSIGNED NOT NULL, total_amount DECIMAL(10,2) NOT NULL, package_snapshot JSON NULL,
  FOREIGN KEY (order_id) REFERENCES orders(id), INDEX idx_item_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_status_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL,
  from_status VARCHAR(20) NULL, to_status VARCHAR(20) NOT NULL, operator_type VARCHAR(20) NOT NULL,
  operator_id BIGINT UNSIGNED NULL, reason VARCHAR(200) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id), INDEX idx_status_order (order_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL, role_code VARCHAR(40) NOT NULL DEFAULT 'admin', status VARCHAR(20) NOT NULL DEFAULT 'active',
  last_login_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_tokens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES admin_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS operation_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL,
  target_type VARCHAR(50) NULL, target_id VARCHAR(60) NULL, ip VARCHAR(45) NULL, detail JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_operation_user_time (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
